version: "3.9"
services:
  web:
    build: .
    command: bash -c "bundle && bin/dev"
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp
      - gem_cache:/gems:delegated
    tty: true
    stdin_open: true

volumes:
  gem_cache: {}
  redis:
